Repository second-hand-team-01/second-hand, pull requests merged in 2023-08, with the labels that each got.

#366 [BE] location Array로 받을수 있도록 수정
  be/build.gradle
  be/src/main/java/codesquad/secondhand/controller/LocationController.java
  be/src/main/java/codesquad/secondhand/dto/location/LocationIdDto.java
  be/src/main/java/codesquad/secondhand/entity/Member.java
  be/src/main/java/codesquad/secondhand/service/ImageService.java
  be/src/main/java/codesquad/secondhand/service/LocationService.java
  be/src/main/resources/schema.sql
  be/src/test/java/codesquad/secondhand/config/TestDummyData.java
Labels: BE

#367 [BE] 요청한 주소와 비슷한 주소 검색 기능 구현
  be/src/main/java/codesquad/secondhand/controller/LocationController.java
  be/src/main/java/codesquad/secondhand/dto/ResponseSetDto.java
  be/src/main/java/codesquad/secondhand/repository/LocationRepository.java
  be/src/main/java/codesquad/secondhand/service/LocationService.java
Labels: BE

#368 [BE] 요청한 주소와 비슷한 주소 검색 기능 구현
  be/src/main/java/codesquad/secondhand/controller/LocationController.java
  be/src/main/java/codesquad/secondhand/dto/ResponseSetDto.java
  be/src/main/java/codesquad/secondhand/repository/LocationRepository.java
  be/src/main/java/codesquad/secondhand/service/LocationService.java
Labels: BE

#369 [BE] 요청한 주소와 비슷한 주소 검색 기능 구현Dev
  be/src/main/java/codesquad/secondhand/controller/LocationController.java
  be/src/main/java/codesquad/secondhand/dto/ResponseSetDto.java
  be/src/main/java/codesquad/secondhand/repository/LocationRepository.java
  be/src/main/java/codesquad/secondhand/service/LocationService.java
Labels: BE

#370 [iOS] Feat: 자동 로그인 기능 구현
  iOS/SecondHand/SecondHand.xcodeproj/project.pbxproj
  iOS/SecondHand/SecondHand/Member/Account/AccountInfoNetworkManager.swift
  iOS/SecondHand/SecondHand/Member/Account/AccountInfoUseCase.swift
  iOS/SecondHand/SecondHand/Member/Account/UI/AccountInfoView.swift
  iOS/SecondHand/SecondHand/Member/Account/UI/AccountViewController.swift
  iOS/SecondHand/SecondHand/Member/SignIn/SignInNetworkManager.swift
  iOS/SecondHand/SecondHand/Member/SignIn/UI/AccountInputView.swift
  iOS/SecondHand/SecondHand/Member/SignIn/UI/IdValidationDelegate.swift
  iOS/SecondHand/SecondHand/Member/SignIn/UI/PasswordValidationDelegate.swift
  iOS/SecondHand/SecondHand/Member/SignIn/UI/SignInButtonGroupView+addAction.swift
  iOS/SecondHand/SecondHand/Member/SignIn/UI/SignInButtonGroupView.swift
  iOS/SecondHand/SecondHand/Member/SignIn/UI/SignInView.swift
  iOS/SecondHand/SecondHand/Member/SignIn/UI/SignInViewController.swift
  iOS/SecondHand/SecondHand/Member/SignUp/SignUpNetworkManager+Error.swift
  iOS/SecondHand/SecondHand/Member/SignUp/UI/SignUpView.swift
  iOS/SecondHand/SecondHand/Member/SignUp/UI/SignUpViewController.swift
  iOS/SecondHand/SecondHand/Network/DTO/SignInResponseDTO.swift
  iOS/SecondHand/SecondHand/Tabbar/TabBarController.swift
Labels: iOS, feat

#371 [iOS] Deisgn: 수정 및 생성 화면 UI 생성
  iOS/SecondHand/SecondHand.xcodeproj/project.pbxproj
  iOS/SecondHand/SecondHand/Detail/UI/DetailViewController.swift
  iOS/SecondHand/SecondHand/Edit/UI/AlbumImageViewer.swift
  iOS/SecondHand/SecondHand/Edit/UI/EditViewController.swift
  iOS/SecondHand/SecondHand/Edit/UI/ProductInputView.swift
  iOS/SecondHand/SecondHand/Extension/UIViewController+setTitle.swift
  iOS/SecondHand/SecondHand/LogManager.swift
Labels: iOS
