Repository second-hand-team-01/second-hand, pull requests merged in 2023-11, with the labels that each got.

#385 [FE] 동네 설정 팝업 및 새로고침시 로그인 유지 기능 구현
  fe/src/components/commons/Button/Button.tsx
  fe/src/components/commons/Dropdown/Dropdown.tsx
  fe/src/components/commons/FilterBar/FilterBar.tsx
  fe/src/components/commons/Icon/Icon.tsx
  fe/src/components/commons/Layout/Layout.tsx
  fe/src/components/commons/Layout/LayoutStyle.ts
  fe/src/components/commons/ListItem/ListItem.tsx
  fe/src/components/commons/LocationPopup/LocationPopup.tsx
  fe/src/components/commons/LocationSelector/LocationSelector.tsx
  fe/src/components/commons/Menu/Menu.tsx
  fe/src/components/commons/Menu/MenuStyle.ts
  fe/src/components/commons/Portal/Portal.tsx
  fe/src/components/commons/ReactQuerySuspense/ReactQuerySuspense.tsx
  fe/src/components/commons/TabBar/TabBar.tsx
  fe/src/components/commons/ToolBar/ToolBar.tsx
  fe/src/constants/login.ts
  fe/src/pages/AuthPage/AuthPage.tsx
  fe/src/pages/ChatDetailsPage/ChatDetailsPage.tsx
  fe/src/pages/ChatPage/ChatPage.tsx
  fe/src/pages/DetailsPage/DetailsPage.tsx
  fe/src/pages/FavoritePage/FavoritePageContents/FavoriteContents.tsx
  fe/src/pages/HomePage/HomeList/HomeList.tsx
  fe/src/pages/HomePage/HomePage.tsx
  fe/src/pages/LoginPage/LoginPage.tsx
  fe/src/pages/SalesHistoryPage/SalesHistoryPage.tsx
  fe/src/pages/WritePage/WritePage.tsx
  fe/src/services/apis/apis.ts
  fe/src/services/items/items.ts
  fe/src/services/items/write.ts
  fe/src/services/locations/locations.ts
  fe/src/services/signUp/signUp.ts
  fe/src/stores/UserContext.tsx
  fe/src/type-store/services/location.ts
Labels: refactor, FE, feat

#388 [FE] 로그인 유효성 검사 로직 수정
  fe/src/pages/LoginPage/LoginPage.tsx
Labels: refactor, FE

#393 feat: add dummy service
  be/src/main/java/codesquad/secondhand/config/WebMvcConfig.java
  be/src/main/java/codesquad/secondhand/controller/DummyController.java
  be/src/main/java/codesquad/secondhand/dto/item/ItemDetailDto.java
  be/src/main/java/codesquad/secondhand/interceptor/BearerAuthInterceptor.java
  be/src/main/java/codesquad/secondhand/service/DummyService.java
  be/src/main/resources/data.sql
  be/src/test/java/codesquad/secondhand/config/DummyURLChange.java
Labels: BE

#394 feat: add dummy service
  be/src/main/java/codesquad/secondhand/config/WebMvcConfig.java
  be/src/main/java/codesquad/secondhand/controller/DummyController.java
  be/src/main/java/codesquad/secondhand/dto/item/ItemDetailDto.java
  be/src/main/java/codesquad/secondhand/interceptor/BearerAuthInterceptor.java
  be/src/main/java/codesquad/secondhand/service/DummyService.java
  be/src/main/resources/data.sql
  be/src/test/java/codesquad/secondhand/config/DummyURLChange.java
Labels: BE

#395 fix: dummy service 로케이션에 맞게 더미 생성 로직 수정
  be/src/main/java/codesquad/secondhand/controller/DummyController.java
  be/src/main/java/codesquad/secondhand/service/DummyService.java
  be/src/main/resources/data.sql
Labels: BE

#396 fix: dummy service 로케이션에 맞게 더미 생성 로직 수정
  be/src/main/java/codesquad/secondhand/controller/DummyController.java
  be/src/main/java/codesquad/secondhand/service/DummyService.java
  be/src/main/resources/data.sql
Labels: BE

#397 fix: dummy service 아이템 제목 변경
  be/src/main/java/codesquad/secondhand/service/DummyService.java
Labels: BE

#398 fix: dummy service 아이템 제목 변경
  be/src/main/java/codesquad/secondhand/service/DummyService.java
Labels: BE

#399 fix: ItemDetailDto 생성자 수정
  be/src/main/java/codesquad/secondhand/dto/item/ItemDetailDto.java
Labels: BE

#400 fix: ItemDetailDto 생성자 수정
  be/src/main/java/codesquad/secondhand/dto/item/ItemDetailDto.java
Labels: BE

#401 [FE] 사용자는 지역선택 로직 수정
  fe/src/components/commons/BottomSheet/BottomSheet.tsx
  fe/src/components/commons/FilterBar/FilterBar.tsx
  fe/src/components/commons/LocationPopup/LocationPopup.tsx
  fe/src/components/commons/LocationSelector/LocationSelector.tsx
  fe/src/pages/HomePage/HomePage.tsx
  fe/src/pages/SalesHistoryPage/SalesHistoryPage.tsx
  fe/src/stores/UserContext.tsx
Labels: refactor, FE

#403 Dev -> main
  fe/src/components/commons/BottomSheet/BottomSheet.tsx
  fe/src/components/commons/FilterBar/FilterBar.tsx
  fe/src/components/commons/LocationPopup/LocationPopup.tsx
  fe/src/components/commons/LocationSelector/LocationSelector.tsx
  fe/src/pages/HomePage/HomePage.tsx
  fe/src/pages/SalesHistoryPage/SalesHistoryPage.tsx
  fe/src/stores/UserContext.tsx
Labels: FE

#405 Fe -> dev
  fe/src/pages/HomePage/HomePage.tsx
Labels: refactor, FE

#406 Dev -> main
  fe/src/pages/HomePage/HomePage.tsx
Labels: refactor, FE

#407 Refactor: OAUth 버그 수정을 위한 redirect uri 임시 수정
  be/src/main/resources/application-prod.yml
Labels: chore

#409 Refactor: OAUth 버그 수정을 위한 redirect uri 임시 수정
  be/src/main/resources/application-prod.yml
Labels: chore

#410 Fe 130 사용자는 본인이 등록한 상품의 상태를 변경할 수
  fe/src/pages/AuthPage/AuthPage.tsx
  fe/src/pages/DetailsPage/DetailsPage.tsx
  fe/src/pages/HomePage/HomeList/HomeList.tsx
  fe/src/pages/LoginPage/LoginPage.tsx
  fe/src/pages/SalesHistoryPage/SalesHistoryPage.tsx
  fe/src/pages/WritePage/WritePage.tsx
  fe/src/stores/UserContext.tsx
Labels: refactor, FE

#411 Fe -> dev
  fe/src/pages/AuthPage/AuthPage.tsx
  fe/src/pages/DetailsPage/DetailsPage.tsx
  fe/src/pages/HomePage/HomeList/HomeList.tsx
  fe/src/pages/LoginPage/LoginPage.tsx
  fe/src/pages/SalesHistoryPage/SalesHistoryPage.tsx
  fe/src/pages/WritePage/WritePage.tsx
  fe/src/stores/UserContext.tsx
Labels: refactor, FE

#412 Dev -> Main
  fe/src/pages/AuthPage/AuthPage.tsx
  fe/src/pages/DetailsPage/DetailsPage.tsx
  fe/src/pages/HomePage/HomeList/HomeList.tsx
  fe/src/pages/LoginPage/LoginPage.tsx
  fe/src/pages/SalesHistoryPage/SalesHistoryPage.tsx
  fe/src/pages/WritePage/WritePage.tsx
  fe/src/stores/UserContext.tsx
Labels: refactor, FE
