Repository second-hand-team-01/second-hand, pull requests merged in 2023-06, with the labels that each got.

#15 [FE] Profile 컴포넌트 추가
  fe/.storybook/main.ts
  fe/.storybook/preview.ts
  fe/package.json
  fe/pnpm-lock.yaml
  fe/src/App.tsx
  fe/src/common/Test/Test.stories.ts
  fe/src/common/Test/Test.tsx
  fe/src/common/Test/TestStyle.ts
  fe/src/common/Text/Button.stories.ts
  fe/src/common/Text/Button.tsx
  fe/src/common/Text/ButtonStyle.ts
  fe/src/components/Icon/Icon.tsx
  fe/src/components/Icon/IconStyle.ts
  fe/src/components/Profile/Profile.stories.ts
  fe/src/components/Profile/Profile.tsx
  fe/src/components/Profile/ProfileStyle.ts
  fe/src/components/Test.stories.ts
  fe/src/components/Test.tsx
  fe/src/components/TestStyle.ts
  fe/src/components/index.ts
  fe/src/styles/GlobalStyle.ts
Labels: FE, feat

#18 [FE] TextInput 컴포넌트 추가
  fe/src/components/TextInput/TextInput.stories.ts
  fe/src/components/TextInput/TextInput.tsx
  fe/src/components/TextInput/TextInputStyle.ts
  fe/src/components/index.ts
  fe/src/styles/GlobalStyle.ts
  fe/src/styles/Typography.ts
Labels: FE, feat

#19 [FE] Button 컴포넌트 구현
  fe/pnpm-lock.yaml
  fe/src/components/button/Button.stories.ts
  fe/src/components/button/Button.tsx
  fe/src/components/button/ButtonStyle.ts
Labels: FE, feat

#20 [FE] 폰트 적용이 안되는 버그 수정
  fe/src/App.tsx
  fe/src/components/Icon/IconStyle.ts
  fe/src/index.css
  fe/src/styles/GlobalStyle.ts
Labels: FE, feat

#21 [FE] 아이콘 폰트 적용 버그 수정
  fe/src/App.tsx
  fe/src/components/Icon/IconStyle.ts
  fe/src/styles/index.css
Labels: FE, feat

#23 [FE] 페이지 레이아웃 컴포넌트 추가
  fe/.storybook/preview.ts
  fe/.storybook/style.css
  fe/src/App.tsx
  fe/src/components/commons/Button/Button.stories.ts
  fe/src/components/commons/Button/Button.tsx
  fe/src/components/commons/Button/ButtonStyle.ts
  fe/src/components/commons/ChatBar/ChatBar.tsx
  fe/src/components/commons/ChatBar/ChatBarStyle.ts
  fe/src/components/commons/Dropdown/Dropdown.stories.ts
  fe/src/components/commons/Dropdown/Dropdown.tsx
  fe/src/components/commons/Dropdown/DropdownStyle.ts
  fe/src/components/commons/FilterBar/FilterBar.tsx
  fe/src/components/commons/FilterBar/FilterBarStyle.ts
  fe/src/components/commons/Icon/Icon.stories.ts
  fe/src/components/commons/Icon/Icon.tsx
  fe/src/components/commons/Icon/IconStyle.ts
  fe/src/components/commons/InfoBar/InfoBar.tsx
  fe/src/components/commons/InfoBar/InfoBarStyle.ts
  fe/src/components/commons/Layout/Layout.stories.ts
  fe/src/components/commons/Layout/Layout.tsx
  fe/src/components/commons/Layout/LayoutStyle.ts
  fe/src/components/commons/NavBar/NavBar.tsx
  fe/src/components/commons/NavBar/NavBarStyle.ts
  fe/src/components/commons/Profile/Profile.stories.ts
  fe/src/components/commons/Profile/Profile.tsx
  fe/src/components/commons/Profile/ProfileStyle.ts
  fe/src/components/commons/Tab/Tab.stories.tsx
  fe/src/components/commons/Tab/Tab.tsx
  fe/src/components/commons/Tab/TabStyle.ts
  fe/src/components/commons/TextInput/TextInput.stories.ts
  fe/src/components/commons/TextInput/TextInput.tsx
  fe/src/components/commons/TextInput/TextInputStyle.ts
  fe/src/components/commons/index.ts
  fe/src/components/index.ts
  fe/src/styles/GlobalStyle.ts
Labels: FE, feat

#24 [BE] Swagger 사용을 위한 초기 설정 및 패키지 명 수정
  BE/build.gradle
  BE/src/main/java/codesquad/secondhand/SecondHandApplication.java
  BE/src/main/java/codesquad/secondhand/config/JasyptConfig.java
  BE/src/main/resources/application.yml
  BE/src/test/java/codesquad/secondhand/SecondHandApplicationTests.java
Labels: chore, BE

#34 [BE] Git reset 후 다시 병합
  .gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/codesquad/secondhand/SecondHandApplication.java
  BE/src/main/java/codesquad/secondhand/config/JasyptConfig.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/application.yml
  BE/src/test/java/codesquad/secondhand/SecondHandApplicationTests.java
  README.md
Labels: BE

#35 [BE] Git reset 후 다시 병합
  .gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/codesquad/secondhand/SecondHandApplication.java
  BE/src/main/java/codesquad/secondhand/config/JasyptConfig.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/application.yml
  BE/src/test/java/codesquad/secondhand/SecondHandApplicationTests.java
  README.md
Labels: BE

#22 [FE] gitignore 추가
  .gitignore
  fe/src/styles/GlobalStyle.ts
Labels: FE, feat

#45 [FE] tabbar 컴포넌트 구현
  fe/.gitignore
  fe/package.json
  fe/pnpm-lock.yaml
  fe/src/components/commons/TabBar/TabBar.stories.ts
  fe/src/components/commons/TabBar/TabBar.tsx
  fe/src/components/commons/TabBar/TabBarStyle.ts
Labels: FE, feat

#50 [INFRA] ECR docker image upload test
  .github/workflows/be-aws.yml
Labels: INFRA

#53 [BE] docker install 추가
  .github/workflows/be-aws.yml
Labels: INFRA

#54 [INFRA] docker install 추가
  .github/workflows/be-aws.yml
Labels: INFRA

#55 [BE]: ecr test PR
  be/src/main/java/codesquad/secondhand/SecondHandApplication.java
Labels: BE

#56 [BE] ecr test PR
  be/src/main/java/codesquad/secondhand/SecondHandApplication.java
Labels: BE

#57 [INFRA] docker cache 추가 및 빌드 경로 설정
  .github/workflows/be-aws.yml
Labels: INFRA

#58 [INFRA] docker cache 추가 및 빌드 경로 설정
  .github/workflows/be-aws.yml
Labels: INFRA

#59 [BE] ecr test PR
  be/src/main/java/codesquad/secondhand/SecondHandApplication.java
Labels: BE

#60 [BE] ecr test PR
  be/src/main/java/codesquad/secondhand/SecondHandApplication.java
Labels: BE

#62 [INFRA] jar 빌드 추가 및 도커 파일 생성
  .github/workflows/be-aws.yml
  Dockerfile.be
  Dockerfile.fe
Labels: INFRA

#63 [INFRA] 테스트를 위한 path 설정 변경
  .github/workflows/be-aws.yml
Labels: INFRA

#64 [INFRA] 테스트를 위한 path 설정 변경
  .github/workflows/be-aws.yml
Labels: INFRA

#65 [INFRA] gradle 경로 지정
  .github/workflows/be-aws.yml
Labels: INFRA

#66 [INFRA] gradle 경로 지정
  .github/workflows/be-aws.yml
Labels: INFRA

#67 [INFRA] gradle 경로 지정 수정
  .github/workflows/be-aws.yml
Labels: INFRA

#68 [INFRA] gradle 경로 지정 수정
  .github/workflows/be-aws.yml
Labels: INFRA

#70 [INFRA] Dockerfile 경로 수정 및 파일 이름 명시
  .github/workflows/be-aws.yml
Labels: INFRA

#72 [INFRA] Dockerfile 경로 수정
  .github/workflows/be-aws.yml
Labels: INFRA

#73 [INFRA] be-aws.yml 순서 변경
  .github/workflows/be-aws.yml
Labels: INFRA

#74 [INFRA] be-aws.yml 순서 변경
  .github/workflows/be-aws.yml
Labels: INFRA

#76 [INFRA] be-aws.yml github.workspace 사용
  .github/workflows/be-aws.yml
Labels: INFRA

#77 [INFRA] be-aws.yml github.workspace 사용
  .github/workflows/be-aws.yml
Labels: INFRA

#78 [INFRA] Dockerfile.be 내부 openjdk 버전 수정
  Dockerfile.be
Labels: INFRA

#79 [INFRA] Dockerfile.be 내부 openjdk 버전 수정
  Dockerfile.be
Labels: INFRA

#81 [INFRA] ARG 경로 수정
  Dockerfile.be
Labels: INFRA

#82 [INFRA] ARG 경로 수정
  Dockerfile.be
Labels: INFRA

#83 [INFRA] Dockerfile.be 내부 ARG JAR_FILE 경로 수정
  Dockerfile.be
Labels: INFRA

#84 [INFRA] Dockerfile.be 내부 ARG JAR_FILE 경로 수정
  Dockerfile.be
Labels: INFRA

#88 [INFRA] JDK 캐싱, docker install 삭제
  .github/workflows/be-aws.yml
Labels: INFRA

#89 [INFRA] JDK 캐싱, docker install 삭제
  .github/workflows/be-aws.yml
Labels: INFRA

#91 [INFRA] docker buildx 미사용
  .github/workflows/be-aws.yml
Labels: INFRA

#93 [INFRA] Dockerfile.be ARG 업데이트
  Dockerfile.be
Labels: INFRA

#94 [INFRA] fe-aws 추가 및 be-aws 수정
  .github/workflows/be-aws.yml
  .github/workflows/fe-aws.yml
Labels: INFRA

#95 [INFRA] fe-aws 추가 및 be-aws 수정
  .github/workflows/be-aws.yml
  .github/workflows/fe-aws.yml
Labels: INFRA

#96 [INFRA] Dockerfile.fe 추가
  Dockerfile.fe
Labels: INFRA

#97 [INFRA] Dockerfile.fe 빌드 경로 수정
  .github/workflows/fe-aws.yml
Labels: INFRA

#98 [INFRA] Dockerfile.fe 빌드 경로 수정
  .github/workflows/fe-aws.yml
  Dockerfile.fe
Labels: INFRA

#100 [INFRA] be-aws.yml 파일 ecs 적용
  .github/workflows/be-aws.yml
Labels: INFRA

#101 [INFRA] be-aws.yml 파일 이미지 태깅 수정
  .github/workflows/be-aws.yml
Labels: INFRA

#102 [INFRA] be-aws.yml 파일 이미지 태깅 수정
  .github/workflows/be-aws.yml
Labels: INFRA

#104 [INFRA] be-aws.yml 테스크 정의 수정
  .github/workflows/be-aws.yml
Labels: INFRA

#105 [INFRA] be-aws.yml 테스크 정의 삭제
  .github/workflows/be-aws.yml
Labels: INFRA

#106 [INFRA] be-aws.yml 테스크 정의 삭제
  .github/workflows/be-aws.yml
Labels: INFRA

#46 [FE] Slide 컴포넌트 추가
  fe/src/components/commons/Slide/Slide.stories.ts
  fe/src/components/commons/Slide/Slide.tsx
  fe/src/components/commons/Slide/SlidePageIndicator/SlidePageIndicator.tsx
  fe/src/components/commons/Slide/SlidePageIndicator/SlidePageIndicatorStyle.ts
  fe/src/components/commons/Slide/SlideStyle.ts
  fe/src/components/commons/index.ts
  fe/src/services/slide.ts
Labels: FE, feat

#75 [FE] BottomSheet 컴포넌트 추가
  fe/.storybook/style.css
  fe/public/index.html
  fe/src/assets/icons/index.ts
  fe/src/components/commons/BottomSheet/BottomSheet.stories.tsx
  fe/src/components/commons/BottomSheet/BottomSheet.tsx
  fe/src/components/commons/BottomSheet/BottomSheetStyle.ts
  fe/src/components/commons/Button/Button.tsx
  fe/src/components/commons/Button/ButtonStyle.ts
  fe/src/components/commons/Icon/IconStyle.ts
  fe/src/components/commons/TextInput/TextInput.tsx
  fe/src/components/commons/TextInput/TextInputStyle.ts
  fe/src/components/commons/index.ts
  fe/src/styles/GlobalStyle.ts
Labels: FE, feat

#80 [FE] listItem 컴포넌트 구현
  fe/src/components/commons/InfoBar/InfoBarStyle.ts
  fe/src/components/commons/ListItem/ListItem.stories.ts
  fe/src/components/commons/ListItem/ListItem.tsx
  fe/src/components/commons/ListItem/ListItemStyle.ts
Labels: FE, feat

#107 [FE] be 폴더 날리기 및 fe 정리
  BE/.gitignore
  BE/.idea/.gitignore
  BE/.idea/.name
  BE/.idea/compiler.xml
  BE/.idea/jarRepositories.xml
  BE/.idea/vcs.xml
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/codesquad/secondhand/SecondHandApplication.java
  BE/src/main/java/codesquad/secondhand/config/JasyptConfig.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/application.yml
  BE/src/test/java/codesquad/secondhand/SecondHandApplicationTests.java
  fe/.eslintignore
  fe/src/components/commons/BottomSheet/BottomSheet.tsx
  fe/src/components/commons/ChatBar/ChatBarStyle.ts
  fe/src/components/commons/Dialog/Dialog.tsx
  fe/src/components/commons/FilterBar/FilterBarStyle.ts
  fe/src/components/commons/InfoBar/InfoBarStyle.ts
  fe/src/components/commons/SnackBar/SnackBar.tsx
  fe/src/components/commons/TextInput/TextInputStyle.ts
Labels: FE, feat

#110 [INFRA] be-aws, fe-aws ecs 연동
  .github/workflows/be-aws.yml
  .github/workflows/fe-aws.yml
  Dockerfile.fe
  nginx.conf
Labels: INFRA

#111 [INFRA] be-aws, fe-aws ecs 연동
  .github/workflows/be-aws.yml
  .github/workflows/fe-aws.yml
  Dockerfile.fe
  nginx.conf
Labels: INFRA

#112 [BE] Item API 작성을 위한 부수적인 파일 생성 및 초기 설정
  be/build.gradle
  be/src/main/java/codesquad/secondhand/controller/ItemController.java
  be/src/main/java/codesquad/secondhand/domain/Category.java
  be/src/main/java/codesquad/secondhand/domain/Interest.java
  be/src/main/java/codesquad/secondhand/domain/Item.java
  be/src/main/java/codesquad/secondhand/domain/ItemImage.java
  be/src/main/java/codesquad/secondhand/domain/Location.java
  be/src/main/java/codesquad/secondhand/domain/Member.java
  be/src/main/java/codesquad/secondhand/repository/ItemRepository.java
  be/src/main/java/codesquad/secondhand/service/ItemService.java
  be/src/main/resources/application.properties
  be/src/main/resources/application.yml
  be/src/main/resources/schema.sql
Labels: BE

#113 [INFRA] 서비스 네임 검색 추가
  .github/workflows/be-aws.yml
  .github/workflows/fe-aws.yml
  be/build.gradle
  be/src/main/java/codesquad/secondhand/controller/ItemController.java
  be/src/main/java/codesquad/secondhand/domain/Category.java
  be/src/main/java/codesquad/secondhand/domain/Interest.java
  be/src/main/java/codesquad/secondhand/domain/Item.java
  be/src/main/java/codesquad/secondhand/domain/ItemImage.java
  be/src/main/java/codesquad/secondhand/domain/Location.java
  be/src/main/java/codesquad/secondhand/domain/Member.java
  be/src/main/java/codesquad/secondhand/repository/ItemRepository.java
  be/src/main/java/codesquad/secondhand/service/ItemService.java
  be/src/main/resources/application.properties
  be/src/main/resources/application.yml
  be/src/main/resources/schema.sql
Labels: BE, INFRA

#114 [INFRA, BE] 서비스 네임 검색 추가, API 기초 설계
  .github/workflows/be-aws.yml
  .github/workflows/fe-aws.yml
  be/build.gradle
  be/src/main/java/codesquad/secondhand/controller/ItemController.java
  be/src/main/java/codesquad/secondhand/domain/Category.java
  be/src/main/java/codesquad/secondhand/domain/Interest.java
  be/src/main/java/codesquad/secondhand/domain/Item.java
  be/src/main/java/codesquad/secondhand/domain/ItemImage.java
  be/src/main/java/codesquad/secondhand/domain/Location.java
  be/src/main/java/codesquad/secondhand/domain/Member.java
  be/src/main/java/codesquad/secondhand/repository/ItemRepository.java
  be/src/main/java/codesquad/secondhand/service/ItemService.java
  be/src/main/resources/application.properties
  be/src/main/resources/application.yml
  be/src/main/resources/schema.sql
Labels: BE, INFRA

#116 [FE] FE -> DEV 병합
  fe/package.json
  fe/pnpm-lock.yaml
  fe/src/components/commons/ListItem/ListItem.tsx
Labels: common

#118 [BE] 카테고리 API 관련 작업 완료
  be/src/main/java/codesquad/secondhand/controller/CategoryController.java
  be/src/main/java/codesquad/secondhand/domain/Category.java
  be/src/main/java/codesquad/secondhand/domain/Location.java
  be/src/main/java/codesquad/secondhand/domain/Member.java
  be/src/main/java/codesquad/secondhand/dto/ResponseDto.java
  be/src/main/java/codesquad/secondhand/dto/StatusCode.java
  be/src/main/java/codesquad/secondhand/dto/category/CategoryDto.java
  be/src/main/java/codesquad/secondhand/repository/CategoryRepository.java
  be/src/main/java/codesquad/secondhand/service/CategoryService.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
Labels: BE, feat

#119 [INFRA, BE] be-aws 파일 변경 및 api 기초 설계
  .github/workflows/be-aws.yml
  be/src/main/java/codesquad/secondhand/controller/CategoryController.java
  be/src/main/java/codesquad/secondhand/domain/Category.java
  be/src/main/java/codesquad/secondhand/domain/Location.java
  be/src/main/java/codesquad/secondhand/domain/Member.java
  be/src/main/java/codesquad/secondhand/dto/ResponseDto.java
  be/src/main/java/codesquad/secondhand/dto/StatusCode.java
  be/src/main/java/codesquad/secondhand/dto/category/CategoryDto.java
  be/src/main/java/codesquad/secondhand/repository/CategoryRepository.java
  be/src/main/java/codesquad/secondhand/service/CategoryService.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
Labels: BE, INFRA

#120 [INFRA, BE] be-aws 파일 변경 및 api 기초 설계
  .github/workflows/be-aws.yml
  be/src/main/java/codesquad/secondhand/controller/CategoryController.java
  be/src/main/java/codesquad/secondhand/domain/Category.java
  be/src/main/java/codesquad/secondhand/domain/Location.java
  be/src/main/java/codesquad/secondhand/domain/Member.java
  be/src/main/java/codesquad/secondhand/dto/ResponseDto.java
  be/src/main/java/codesquad/secondhand/dto/StatusCode.java
  be/src/main/java/codesquad/secondhand/dto/category/CategoryDto.java
  be/src/main/java/codesquad/secondhand/repository/CategoryRepository.java
  be/src/main/java/codesquad/secondhand/service/CategoryService.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
Labels: BE, INFRA

#121 [BE] 더미 데이터 추가 작업 완료
  be/src/main/resources/data.sql
Labels: BE, feat

#122 [INFRA, BE] task definition 변수 변경 및 DB 더미데이터 추가
  .github/workflows/be-aws.yml
  be/src/main/resources/data.sql
Labels: BE, INFRA

#123 [INFRA, BE] task definition 변수 변경 및 DB 더미데이터 추가
  .github/workflows/be-aws.yml
  be/src/main/resources/data.sql
Labels: BE, INFRA

#124 [BE] Location API 관련 작업 완료
  be/src/main/java/codesquad/secondhand/controller/LocationController.java
  be/src/main/java/codesquad/secondhand/domain/Location.java
  be/src/main/java/codesquad/secondhand/dto/location/LocationDto.java
  be/src/main/java/codesquad/secondhand/repository/LocationRepository.java
  be/src/main/java/codesquad/secondhand/service/CategoryService.java
  be/src/main/java/codesquad/secondhand/service/LocationService.java
Labels: BE, feat

#125 [INFRA, BE] task definition json 형식 변경 및 Location api 구성
  .github/workflows/be-aws.yml
  be/src/main/java/codesquad/secondhand/controller/LocationController.java
  be/src/main/java/codesquad/secondhand/domain/Location.java
  be/src/main/java/codesquad/secondhand/dto/location/LocationDto.java
  be/src/main/java/codesquad/secondhand/repository/LocationRepository.java
  be/src/main/java/codesquad/secondhand/service/CategoryService.java
  be/src/main/java/codesquad/secondhand/service/LocationService.java
Labels: BE, INFRA

#126 [INFRA, BE] task definition json 형식 변경 및 Location api 구성
  .github/workflows/be-aws.yml
  be/src/main/java/codesquad/secondhand/controller/LocationController.java
  be/src/main/java/codesquad/secondhand/domain/Location.java
  be/src/main/java/codesquad/secondhand/dto/location/LocationDto.java
  be/src/main/java/codesquad/secondhand/repository/LocationRepository.java
  be/src/main/java/codesquad/secondhand/service/CategoryService.java
  be/src/main/java/codesquad/secondhand/service/LocationService.java
Labels: BE, INFRA

#127 [INFRA] task definition json 파일 변경
  .github/workflows/be-aws.yml
Labels: INFRA

#128 [INFRA] task definition json 파일 변경
  .github/workflows/be-aws.yml
Labels: INFRA

#129 [FE] FE -> DEV 병합
  fe/src/components/commons/BottomSheet/BottomSheet.tsx
  fe/src/components/commons/NavBar/NavBar.tsx
  fe/src/components/commons/Profile/Profile.tsx
  fe/src/components/commons/SnackBar/SnackBar.tsx
Labels: common

#130 [FE] Dev-> Main 병합
  fe/src/components/commons/BottomSheet/BottomSheet.tsx
  fe/src/components/commons/NavBar/NavBar.tsx
  fe/src/components/commons/Profile/Profile.tsx
  fe/src/components/commons/SnackBar/SnackBar.tsx
Labels: common

#134 [BE] Member API 관련 작업 (추후 더 작업할 예정)
  be/src/main/java/codesquad/secondhand/controller/MemberController.java
  be/src/main/java/codesquad/secondhand/domain/Location.java
  be/src/main/java/codesquad/secondhand/domain/Member.java
  be/src/main/java/codesquad/secondhand/dto/location/LocationTownDto.java
  be/src/main/java/codesquad/secondhand/dto/location/LocationTownMapDto.java
  be/src/main/java/codesquad/secondhand/repository/MemberRepository.java
  be/src/main/java/codesquad/secondhand/service/MemberService.java
Labels: BE, feat

#139 [BE] Location API 추가 작업
  be/src/main/java/codesquad/secondhand/controller/LocationController.java
  be/src/main/java/codesquad/secondhand/controller/MemberController.java
  be/src/main/java/codesquad/secondhand/dto/ResponseListDto.java
  be/src/main/java/codesquad/secondhand/dto/location/LocationTownMapDto.java
  be/src/main/java/codesquad/secondhand/dto/location/MainSubTownDto.java
  be/src/main/java/codesquad/secondhand/service/LocationService.java
  be/src/main/java/codesquad/secondhand/service/MemberService.java
Labels: BE, feat

#140 [INFRA, BE] 워크플로 파일 업데이트 및 api 작업
  .github/workflows/fe-aws.yml
  be/src/main/java/codesquad/secondhand/controller/LocationController.java
  be/src/main/java/codesquad/secondhand/controller/MemberController.java
  be/src/main/java/codesquad/secondhand/domain/Location.java
  be/src/main/java/codesquad/secondhand/domain/Member.java
  be/src/main/java/codesquad/secondhand/dto/ResponseListDto.java
  be/src/main/java/codesquad/secondhand/dto/location/LocationTownDto.java
  be/src/main/java/codesquad/secondhand/dto/location/MainSubTownDto.java
  be/src/main/java/codesquad/secondhand/repository/MemberRepository.java
  be/src/main/java/codesquad/secondhand/service/LocationService.java
  be/src/main/java/codesquad/secondhand/service/MemberService.java
Labels: BE, INFRA

#141 [INFRA, BE] 워크플로 파일 업데이트 및 api 작업
  .github/workflows/fe-aws.yml
  be/src/main/java/codesquad/secondhand/controller/LocationController.java
  be/src/main/java/codesquad/secondhand/controller/MemberController.java
  be/src/main/java/codesquad/secondhand/domain/Location.java
  be/src/main/java/codesquad/secondhand/domain/Member.java
  be/src/main/java/codesquad/secondhand/dto/ResponseListDto.java
  be/src/main/java/codesquad/secondhand/dto/location/LocationTownDto.java
  be/src/main/java/codesquad/secondhand/dto/location/MainSubTownDto.java
  be/src/main/java/codesquad/secondhand/repository/MemberRepository.java
  be/src/main/java/codesquad/secondhand/service/LocationService.java
  be/src/main/java/codesquad/secondhand/service/MemberService.java
Labels: BE, INFRA

#142 [INFRA] 워크플로 순서 변경 및 누락 내용 추가
  .github/workflows/be-aws.yml
  .github/workflows/fe-aws.yml
Labels: BE, INFRA

#143 [INFRA] 워크플로 순서 변경 및 누락 내용 추가
  .github/workflows/be-aws.yml
  .github/workflows/fe-aws.yml
Labels: INFRA

#144 [BE] 코드 주석 처리 해제를 위한 작업
  be/build.gradle
  be/src/main/java/codesquad/secondhand/config/JasyptConfig.java
  be/src/main/java/codesquad/secondhand/controller/CategoryController.java
  be/src/main/java/codesquad/secondhand/controller/ItemController.java
  be/src/main/java/codesquad/secondhand/controller/LocationController.java
  be/src/main/java/codesquad/secondhand/controller/MemberController.java
  be/src/main/java/codesquad/secondhand/domain/Category.java
  be/src/main/java/codesquad/secondhand/domain/Interest.java
  be/src/main/java/codesquad/secondhand/domain/Item.java
  be/src/main/java/codesquad/secondhand/domain/ItemImage.java
  be/src/main/java/codesquad/secondhand/domain/Location.java
  be/src/main/java/codesquad/secondhand/domain/Member.java
  be/src/main/java/codesquad/secondhand/dto/category/CategoryDto.java
  be/src/main/java/codesquad/secondhand/dto/location/LocationDto.java
  be/src/main/java/codesquad/secondhand/dto/location/LocationTownDto.java
  be/src/main/java/codesquad/secondhand/dto/location/MainSubTownDto.java
  be/src/main/java/codesquad/secondhand/repository/CategoryRepository.java
  be/src/main/java/codesquad/secondhand/repository/ItemRepository.java
  be/src/main/java/codesquad/secondhand/repository/LocationRepository.java
  be/src/main/java/codesquad/secondhand/repository/MemberRepository.java
  be/src/main/java/codesquad/secondhand/service/CategoryService.java
  be/src/main/java/codesquad/secondhand/service/ItemService.java
  be/src/main/java/codesquad/secondhand/service/LocationService.java
  be/src/main/java/codesquad/secondhand/service/MemberService.java
  be/src/main/resources/application-local.yml
  be/src/test/java/codesquad/secondhand/config/JasyptConfigTest.java
Labels: BE, feat

#147 [BE] 2주차 PR 피드백 적용 작업
  be/build.gradle
  be/src/main/java/codesquad/secondhand/SecondHandApplication.java
  be/src/main/java/codesquad/secondhand/controller/ItemController.java
  be/src/main/java/codesquad/secondhand/domain/Category.java
  be/src/main/java/codesquad/secondhand/domain/Item.java
  be/src/main/java/codesquad/secondhand/dto/ResponseDto.java
  be/src/main/java/codesquad/secondhand/dto/location/MainSubTownDto.java
  be/src/main/java/codesquad/secondhand/repository/CategoryRepository.java
  be/src/main/java/codesquad/secondhand/repository/ItemRepository.java
  be/src/main/java/codesquad/secondhand/repository/LocationRepository.java
  be/src/main/java/codesquad/secondhand/service/ItemService.java
  be/src/main/java/codesquad/secondhand/service/MemberService.java
  be/src/main/resources/application-local.yml
  be/src/test/java/codesquad/secondhand/config/JasyptConfigTest.java
Labels: BE

#148 [BE] 패키지 명 수정 및 배포 상황에서 사용될 application-prod.yml 추가
  be/src/main/java/codesquad/secondhand/dto/category/CategoryDto.java
  be/src/main/java/codesquad/secondhand/dto/location/LocationDto.java
  be/src/main/java/codesquad/secondhand/dto/location/LocationTownDto.java
  be/src/main/java/codesquad/secondhand/dto/location/MainSubTownDto.java
  be/src/main/java/codesquad/secondhand/entity/Category.java
  be/src/main/java/codesquad/secondhand/entity/Interest.java
  be/src/main/java/codesquad/secondhand/entity/Item.java
  be/src/main/java/codesquad/secondhand/entity/ItemImage.java
  be/src/main/java/codesquad/secondhand/entity/Location.java
  be/src/main/java/codesquad/secondhand/entity/Member.java
  be/src/main/java/codesquad/secondhand/repository/CategoryRepository.java
  be/src/main/java/codesquad/secondhand/repository/ItemRepository.java
  be/src/main/java/codesquad/secondhand/repository/LocationRepository.java
  be/src/main/java/codesquad/secondhand/repository/MemberRepository.java
  be/src/main/java/codesquad/secondhand/service/CategoryService.java
  be/src/main/java/codesquad/secondhand/service/ItemService.java
  be/src/main/java/codesquad/secondhand/service/LocationService.java
  be/src/main/java/codesquad/secondhand/service/MemberService.java
  be/src/main/resources/application-prod.yml
Labels: chore, BE

#150 [INFRA, BE] aws 플로우 파일 수정 및 yml 암호화
  .github/workflows/fe-aws.yml
  Dockerfile.fe
  be/build.gradle
  be/src/main/java/codesquad/secondhand/SecondHandApplication.java
  be/src/main/java/codesquad/secondhand/config/JasyptConfig.java
  be/src/main/java/codesquad/secondhand/controller/CategoryController.java
  be/src/main/java/codesquad/secondhand/controller/ItemController.java
  be/src/main/java/codesquad/secondhand/controller/LocationController.java
  be/src/main/java/codesquad/secondhand/controller/MemberController.java
  be/src/main/java/codesquad/secondhand/domain/Category.java
  be/src/main/java/codesquad/secondhand/domain/Interest.java
  be/src/main/java/codesquad/secondhand/domain/Item.java
  be/src/main/java/codesquad/secondhand/domain/ItemImage.java
  be/src/main/java/codesquad/secondhand/domain/Location.java
  be/src/main/java/codesquad/secondhand/domain/Member.java
  be/src/main/java/codesquad/secondhand/dto/ResponseDto.java
  be/src/main/java/codesquad/secondhand/dto/category/CategoryDto.java
  be/src/main/java/codesquad/secondhand/dto/location/LocationDto.java
  be/src/main/java/codesquad/secondhand/dto/location/LocationTownDto.java
  be/src/main/java/codesquad/secondhand/dto/location/MainSubTownDto.java
  be/src/main/java/codesquad/secondhand/entity/Category.java
  be/src/main/java/codesquad/secondhand/entity/Interest.java
  be/src/main/java/codesquad/secondhand/entity/Item.java
  be/src/main/java/codesquad/secondhand/entity/ItemImage.java
  be/src/main/java/codesquad/secondhand/entity/Location.java
  be/src/main/java/codesquad/secondhand/entity/Member.java
  be/src/main/java/codesquad/secondhand/repository/CategoryRepository.java
  be/src/main/java/codesquad/secondhand/repository/ItemRepository.java
  be/src/main/java/codesquad/secondhand/repository/LocationRepository.java
  be/src/main/java/codesquad/secondhand/repository/MemberRepository.java
  be/src/main/java/codesquad/secondhand/service/CategoryService.java
  be/src/main/java/codesquad/secondhand/service/ItemService.java
  be/src/main/java/codesquad/secondhand/service/LocationService.java
  be/src/main/java/codesquad/secondhand/service/MemberService.java
  be/src/main/resources/application-local.yml
  be/src/main/resources/application-prod.yml
  be/src/main/resources/application.yml
  be/src/test/java/codesquad/secondhand/config/JasyptConfigTest.java
Labels: BE, INFRA

#151 [INFRA] nginx 경로 수정 및 그레이들 테스트 제외
  .github/workflows/be-aws.yml
  Dockerfile.fe
Labels: INFRA

#152 [INFRA] nginx 경로 수정 및 그레이들 테스트 제외
  .github/workflows/be-aws.yml
  Dockerfile.fe
Labels: INFRA

#153 [BE] Category API 내부 ResponseListDto를 사용하여 반환하도록 코드 수정
  be/src/main/java/codesquad/secondhand/controller/CategoryController.java
Labels: refactor, BE

#154 [INFRA, BE] dockerfile 수정 및 Dto 수정
  Dockerfile.fe
  be/src/main/java/codesquad/secondhand/controller/CategoryController.java
Labels: BE, INFRA

#155 [INFRA, BE] dockerfile 수정 및 Dto 수정
  Dockerfile.fe
  be/src/main/java/codesquad/secondhand/controller/CategoryController.java
Labels: BE, INFRA

#156 [INFRA] Dockerfile.fe nginx 경로 수정3
  Dockerfile.fe
Labels: INFRA

#157 [INFRA] Dockerfile.fe nginx 경로 수정3
  .idea/.gitignore
  .idea/git_toolbox_prj.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/second-hand.iml
  .idea/vcs.xml
  Dockerfile.fe
Labels: INFRA

#158 [INFRA] aws 파일 수정 및 경로 수정
  .github/workflows/fe-aws.yml
  Dockerfile.fe
Labels: INFRA

#159 [INFRA] aws 파일 수정 및 경로 수정
  .github/workflows/fe-aws.yml
  Dockerfile.fe
Labels: INFRA

#160 [BE] mysql 버전 변경
  be/build.gradle
Labels: BE

#161 [BE] mysql 버전 변경
  be/build.gradle
Labels: BE

#162 [BE] datasource password key 변경
  be/src/main/resources/application-prod.yml
Labels: BE

#163 [BE] datasource password key 변경
  be/src/main/resources/application-prod.yml
Labels: BE

#164 [INFRA] 암호화 키 변경 및 서버 정보 추가
  be/src/main/resources/application-prod.yml
  nginx.conf
Labels: INFRA

#165 [INFRA] 암호화 키 변경 및 서버 정보 추가
  be/src/main/resources/application-prod.yml
  nginx.conf
Labels: INFRA

#145 [FE] API 관련 환경설정
  fe/package.json
  fe/pnpm-lock.yaml
  fe/src/constants/apis.ts
  fe/src/constants/error.ts
  fe/src/hooks/useData/useData.test.ts
  fe/src/hooks/useData/useData.ts
  fe/src/mocks/handlers.ts
  fe/src/mocks/index.ts
  fe/src/services/apis/api.test.ts
  fe/src/services/apis/apis.ts
  fe/src/services/login/login.ts
  fe/src/services/slide/slide.ts
  fe/src/utils/common/common.test.ts
  fe/src/utils/common/common.ts
  fe/tsconfig.json
Labels: FE, feat

#166 [FE] Menu 컴포넌트 구현
  fe/src/App.tsx
  fe/src/components/commons/BottomSheet/BottomSheetStyle.ts
  fe/src/components/commons/Menu/Menu.stories.ts
  fe/src/components/commons/Menu/Menu.tsx
  fe/src/components/commons/Menu/MenuStyle.ts
  fe/src/components/commons/NavBar/NavBarStyle.ts
  fe/src/components/commons/SnackBar/SnackBarStyle.ts
  fe/src/components/commons/TextInput/TextInputStyle.ts
  fe/src/styles/GlobalStyle.ts
  fe/src/styles/Typography.ts
  fe/src/styles/styled.d.ts
  fe/src/styles/theme.ts
Labels: FE, feat

#167 [INFRA, BE] 리버스 프록시 추가
  nginx.conf
Labels: BE, INFRA

#168 [INFRA, BE] 리버스 프록시 추가
  nginx.conf
Labels: BE, INFRA

#171 [FE] 페이지 라우터 설정
  fe/.storybook/preview.ts
  fe/src/App.tsx
  fe/src/components/commons/Layout/Layout.tsx
  fe/src/components/commons/Layout/LayoutStyle.ts
  fe/src/components/commons/Slide/Slide.tsx
  fe/src/components/commons/TabBar/TabBar.tsx
  fe/src/constants/routes.tsx
  fe/src/services/apis/apis.ts
  fe/src/styles/GlobalStyle.ts
Labels: FE, feat

#172 [BE] ChatRoom 엔티티 생성 및 Item 리스트 페이지네이션 구현
  be/src/main/java/codesquad/secondhand/controller/ItemController.java
  be/src/main/java/codesquad/secondhand/dto/item/ItemDto.java
  be/src/main/java/codesquad/secondhand/dto/item/ItemSliceDto.java
  be/src/main/java/codesquad/secondhand/entity/ChatRoom.java
  be/src/main/java/codesquad/secondhand/entity/Item.java
  be/src/main/java/codesquad/secondhand/repository/ChatRoomRepository.java
  be/src/main/java/codesquad/secondhand/repository/InterestRepository.java
  be/src/main/java/codesquad/secondhand/repository/ItemRepository.java
  be/src/main/java/codesquad/secondhand/service/ItemService.java
  be/src/main/resources/data.sql
Labels: BE, feat

#173 [INFRA, BE] Dto 수정 및 네임스페이스 적용
  be/src/main/java/codesquad/secondhand/controller/ItemController.java
  be/src/main/java/codesquad/secondhand/dto/item/ItemDto.java
  be/src/main/java/codesquad/secondhand/dto/item/ItemSliceDto.java
  be/src/main/java/codesquad/secondhand/entity/ChatRoom.java
  be/src/main/java/codesquad/secondhand/entity/Item.java
  be/src/main/java/codesquad/secondhand/repository/ChatRoomRepository.java
  be/src/main/java/codesquad/secondhand/repository/InterestRepository.java
  be/src/main/java/codesquad/secondhand/repository/ItemRepository.java
  be/src/main/java/codesquad/secondhand/service/ItemService.java
  be/src/main/resources/data.sql
  nginx.conf
Labels: BE, INFRA

#174 [INFRA, BE] Dto 수정 및 네임스페이스 적용
  be/src/main/java/codesquad/secondhand/controller/ItemController.java
  be/src/main/java/codesquad/secondhand/dto/item/ItemDto.java
  be/src/main/java/codesquad/secondhand/dto/item/ItemSliceDto.java
  be/src/main/java/codesquad/secondhand/entity/ChatRoom.java
  be/src/main/java/codesquad/secondhand/entity/Item.java
  be/src/main/java/codesquad/secondhand/repository/ChatRoomRepository.java
  be/src/main/java/codesquad/secondhand/repository/InterestRepository.java
  be/src/main/java/codesquad/secondhand/repository/ItemRepository.java
  be/src/main/java/codesquad/secondhand/service/ItemService.java
  be/src/main/resources/data.sql
  nginx.conf
Labels: BE, INFRA

#175 [INFRA] 리버스 프록시 삭제
  nginx.conf
Labels: INFRA

#176 [INFRA] 리버스 프록시 삭제
  nginx.conf
Labels: INFRA

#178 [BE] 인크립트 키 수정
  be/src/main/resources/application-prod.yml
Labels: BE

#179 [iOS] 10개식 로딩되도록 페이지 구현
  iOS/SecondHand/SecondHand.xcodeproj/project.pbxproj
  iOS/SecondHand/SecondHand/ItemList/IssueListItem.swift
  iOS/SecondHand/SecondHand/ItemList/ItemListTableViewCell.swift
  iOS/SecondHand/SecondHand/ItemList/ItemListViewController.swift
  iOS/SecondHand/SecondHand/ItemList/Network.swift
  iOS/SecondHand/SecondHand/ItemList/View/CapsuleLabel.swift
  iOS/SecondHand/SecondHand/ItemList/View/LeadingIconLabel.swift
  iOS/SecondHand/SecondHand/ItemList/View/LocationLabel.swift
  iOS/SecondHand/SecondHand/ItemList/View/PriceLabel.swift
  iOS/SecondHand/SecondHand/ItemList/View/TimeLabel.swift
  iOS/SecondHand/SecondHand/ItemList/View/TitleLabel.swift
  iOS/SecondHand/SecondHand/ShareComponent/ColorPalette.swift
Labels: iOS

#180 Ios 38 우드 pr 리뷰 반영
  iOS/SecondHand/SecondHand.xcodeproj/project.pbxproj
  iOS/SecondHand/SecondHand/Detail/DetailContentView+layoutConstraint.swift
  iOS/SecondHand/SecondHand/Detail/DetailContentView.swift
  iOS/SecondHand/SecondHand/Detail/DetailViewController+layoutScrollView.swift
  iOS/SecondHand/SecondHand/Detail/DetailViewController.swift
  iOS/SecondHand/SecondHand/Detail/SellerInfo.swift
  iOS/SecondHand/SecondHand/Detail/UI/CommunicationInfo.swift
  iOS/SecondHand/SecondHand/Detail/UI/DetailContentView.swift
  iOS/SecondHand/SecondHand/Detail/UI/DetailToolbar.swift
  iOS/SecondHand/SecondHand/Detail/UI/ProductInfo.swift
  iOS/SecondHand/SecondHand/Detail/UI/SellerInfo.swift
  iOS/SecondHand/SecondHand/ShareComponent/Typography.swift
  iOS/SecondHand/SecondHand/ShareComponent/UIFont+Typography.swift
  iOS/SecondHand/SecondHand/ViewController.swift
Labels: iOS

#181 [BE] location 요청 경로 변경
  be/src/main/java/codesquad/secondhand/controller/LocationController.java
Labels: BE

#182 [BE] location 요청 경로 변경
  be/src/main/java/codesquad/secondhand/controller/LocationController.java
Labels: BE

#183 [BE] JWT 의존성 추가
  be/build.gradle
Labels: BE, feat

#185 [INFRA, BE] JWT 의존성 및 server name 변경
  .github/workflows/be-aws.yml
  .github/workflows/fe-aws.yml
  be/build.gradle
  nginx.conf
Labels: BE, INFRA

#186 [INFRA, BE] JWT 의존성 및 server name 변경
  .github/workflows/be-aws.yml
  .github/workflows/fe-aws.yml
  be/build.gradle
  nginx.conf
Labels: BE, INFRA

#187 [INFRA] path 주석 처리
  .github/workflows/be-aws.yml
  .github/workflows/fe-aws.yml
Labels: INFRA

#188 [INFRA] path 주석 처리
  .github/workflows/be-aws.yml
  .github/workflows/fe-aws.yml
Labels: INFRA

#189 [INFRA] CI/CD 1차 완성
  .github/workflows/be-aws.yml
  .github/workflows/fe-aws.yml
Labels: INFRA

#190 [INFRA] CI/CD 1차 완성
  .github/workflows/be-aws.yml
  .github/workflows/fe-aws.yml
Labels: INFRA

#184 [FE] 현재 동네에서 거래되고 있는 상품을 볼 수 있다
  fe/.eslintignore
  fe/package.json
  fe/pnpm-lock.yaml
  fe/public/mockServiceWorker.js
  fe/src/App.tsx
  fe/src/components/commons/BottomSheet/BottomSheet.tsx
  fe/src/components/commons/Button/ButtonStyle.ts
  fe/src/components/commons/ChatBar/ChatBarStyle.ts
  fe/src/components/commons/Dialog/Dialog.tsx
  fe/src/components/commons/FilterBar/FilterBar.tsx
  fe/src/components/commons/FilterBar/FilterBarStyle.ts
  fe/src/components/commons/InfoBar/InfoBarStyle.ts
  fe/src/components/commons/Layout/Layout.tsx
  fe/src/components/commons/Layout/LayoutStyle.ts
  fe/src/components/commons/ListItem/ListItem.tsx
  fe/src/components/commons/ListItem/ListItemStyle.ts
  fe/src/components/commons/NavBar/NavBar.tsx
  fe/src/components/commons/NavBar/NavBarStyle.ts
  fe/src/components/commons/NavBar/Navbar.stories.tsx
  fe/src/components/commons/Profile/Profile.tsx
  fe/src/components/commons/SnackBar/SnackBar.tsx
  fe/src/components/commons/Spinner/Spinner.stories.tsx
  fe/src/components/commons/Spinner/Spinner.tsx
  fe/src/components/commons/Spinner/SpinnerStyle.ts
  fe/src/components/commons/index.ts
  fe/src/constants/error.ts
  fe/src/constants/routes.tsx
  fe/src/constants/style.ts
  fe/src/hooks/useData/useData.test.ts
  fe/src/hooks/useData/useData.ts
  fe/src/hooks/useFetch/useFetch.ts
  fe/src/hooks/useIntersectionObserver/useIntersectionObserver.ts
  fe/src/mocks/browser.ts
  fe/src/mocks/data/items/page0.json
  fe/src/mocks/data/items/page1.json
  fe/src/mocks/data/items/page2.json
  fe/src/mocks/handlers.ts
  fe/src/pages/Home/Home.tsx
  fe/src/pages/Home/HomeStyle.ts
  fe/src/pages/index.tsx
  fe/src/services/apis/apis.ts
  fe/src/services/items/items.ts
  fe/src/styles/GlobalStyle.ts
  fe/src/type-store/items.ts
  fe/src/utils/common/common.test.ts
  fe/src/utils/common/common.ts
  fe/tsconfig.json
Labels: FE, feat

#192 [BE] JWT를 이용한 로그인 구현 작업 (미완)
  be/src/main/java/codesquad/secondhand/config/WebMvcConfig.java
  be/src/main/java/codesquad/secondhand/controller/MemberController.java
  be/src/main/java/codesquad/secondhand/dto/location/LocationDto.java
  be/src/main/java/codesquad/secondhand/dto/location/MainSubDto.java
  be/src/main/java/codesquad/secondhand/dto/member/LoginRequestDto.java
  be/src/main/java/codesquad/secondhand/dto/member/MemberIdxLoginIdDto.java
  be/src/main/java/codesquad/secondhand/dto/member/MemberInfoDto.java
  be/src/main/java/codesquad/secondhand/dto/member/SignUpRequestDto.java
  be/src/main/java/codesquad/secondhand/dto/member/SignUpResponseDto.java
  be/src/main/java/codesquad/secondhand/dto/token/TokenResponse.java
  be/src/main/java/codesquad/secondhand/entity/Location.java
  be/src/main/java/codesquad/secondhand/entity/Member.java
  be/src/main/java/codesquad/secondhand/interceptor/BearerAuthInterceptor.java
  be/src/main/java/codesquad/secondhand/jwt/AuthorizationExtractor.java
  be/src/main/java/codesquad/secondhand/jwt/JwtTokenProvider.java
  be/src/main/java/codesquad/secondhand/repository/MemberRepository.java
  be/src/main/java/codesquad/secondhand/service/MemberService.java
  be/src/main/resources/application-local.yml
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
  be/src/test/java/codesquad/secondhand/config/JasyptConfigTest.java
Labels: BE, feat

#193 [BE] 검증을 위한 초기 설정
  be/build.gradle
  be/src/main/java/codesquad/secondhand/dto/member/SignUpRequestDto.java
  be/src/main/java/codesquad/secondhand/service/MemberService.java
Labels: BE, feat

#195 [BE] 자체 회원 가입 기능 추가
  be/src/main/java/codesquad/secondhand/controller/MemberController.java
  be/src/main/java/codesquad/secondhand/dto/ResponseDto.java
  be/src/main/java/codesquad/secondhand/dto/location/LocationDto.java
  be/src/main/java/codesquad/secondhand/dto/member/SaveMemberDto.java
  be/src/main/java/codesquad/secondhand/dto/member/SignUpRequestDto.java
  be/src/main/java/codesquad/secondhand/entity/Member.java
  be/src/main/java/codesquad/secondhand/exception/code/ItemImageErrorCode.java
  be/src/main/java/codesquad/secondhand/exception/code/MemberErrorCode.java
  be/src/main/java/codesquad/secondhand/service/MemberService.java
Labels: BE, feat

#196 [Be] item upload 구현
  be/build.gradle
  be/src/main/java/codesquad/secondhand/config/S3Config.java
  be/src/main/java/codesquad/secondhand/controller/CategoryController.java
  be/src/main/java/codesquad/secondhand/controller/ItemController.java
  be/src/main/java/codesquad/secondhand/repository/ItemImageRepository.java
  be/src/main/java/codesquad/secondhand/service/ItemImageService.java
  be/src/main/resources/application-local.yml
  be/src/main/resources/application-prod.yml
  be/src/test/java/codesquad/secondhand/config/JasyptConfigTest.java
Labels: BE

#198 [BE] memberIdx 사용을 위한 설정 및 예외 처리 추가
  be/src/main/java/codesquad/secondhand/config/WebMvcConfig.java
  be/src/main/java/codesquad/secondhand/controller/MemberController.java
  be/src/main/java/codesquad/secondhand/dto/member/SignUpRequestDto.java
  be/src/main/java/codesquad/secondhand/exception/code/MemberErrorCode.java
  be/src/main/java/codesquad/secondhand/service/MemberService.java
Labels: BE, feat

#199 [Be] 이미지 업로드 구현
  be/src/main/java/codesquad/secondhand/service/ImageService.java
  be/src/main/java/codesquad/secondhand/service/ItemImageService.java
  be/src/main/java/codesquad/secondhand/service/MemberService.java
  be/src/main/resources/application-local.yml
  be/src/main/resources/schema.sql
Labels: BE

#200 [BE] 기존 loginId를 매개변수로 사용하던 로직 memberIdx를 사용하도록 수정
  be/src/main/java/codesquad/secondhand/controller/MemberController.java
  be/src/main/java/codesquad/secondhand/dto/member/MemberIdxTokenDto.java
  be/src/main/java/codesquad/secondhand/exception/code/MemberErrorCode.java
  be/src/main/java/codesquad/secondhand/interceptor/BearerAuthInterceptor.java
  be/src/main/java/codesquad/secondhand/jwt/JwtTokenProvider.java
  be/src/main/java/codesquad/secondhand/service/MemberService.java
Labels: BE, feat

#201 [BE] `member` 테이블 `refresh_token` 컬럼 추가
  be/src/main/resources/schema.sql
Labels: BE, feat

#206 [BE] aws starter 수정
  be/build.gradle
Labels: BE

#207 [BE] aws starter 수정
  be/build.gradle
Labels: BE

#208 [BE] aws SDK 의존성 제거
  be/build.gradle
  be/src/main/resources/application-prod.yml
Labels: BE

#209 [BE] aws SDK 의존성 제거
  be/build.gradle
  be/src/main/resources/application-prod.yml
Labels: BE

#212 Chore: pnpm -> npm 으로 변경
  fe/package-lock.json
  fe/pnpm-lock.yaml
Labels: chore

#213 [FE] FE -> FE merge
  fe/package-lock.json
  fe/pnpm-lock.yaml
Labels: common

#214 [FE] DEV -> MAIN merge
  fe/package-lock.json
  fe/pnpm-lock.yaml
Labels: common

#215 [FE] testing library hook 삭제
  fe/package-lock.json
  fe/package.json
Labels: FE, feat

#216 [FE] FE -> DEV merge
  fe/package-lock.json
  fe/package.json
Labels: common

#217 [FE] Dev->Main
  fe/package-lock.json
  fe/package.json
Labels: common, feat

#218 [FE] eslint 에러 해결
  fe/src/components/commons/Button/Button.tsx
  fe/src/constants/routes.tsx
  fe/src/mocks/handlers.ts
  fe/src/pages/WritePage/WritePage.tsx
  fe/src/services/items/items.ts
  fe/src/utils/common/common.ts
Labels: FE

#219 [FE] FE -> DEV merge
  fe/src/components/commons/Button/Button.tsx
  fe/src/constants/routes.tsx
  fe/src/mocks/handlers.ts
  fe/src/pages/WritePage/WritePage.tsx
  fe/src/services/items/items.ts
  fe/src/utils/common/common.ts
Labels: common

#220 [FE] Dev -> Main merge
  fe/src/components/commons/Button/Button.tsx
  fe/src/constants/routes.tsx
  fe/src/mocks/handlers.ts
  fe/src/pages/WritePage/WritePage.tsx
  fe/src/services/items/items.ts
  fe/src/utils/common/common.ts
Labels: common

#222 [BE] OAuth 로그인 구현
  be/build.gradle
  be/src/main/java/codesquad/secondhand/config/OauthConfig.java
  be/src/main/java/codesquad/secondhand/controller/OauthController.java
  be/src/main/java/codesquad/secondhand/dto/oauth/MemberProfile.java
  be/src/main/java/codesquad/secondhand/dto/oauth/OauthLoginResponse.java
  be/src/main/java/codesquad/secondhand/dto/oauth/OauthTokenResponse.java
  be/src/main/java/codesquad/secondhand/entity/Member.java
  be/src/main/java/codesquad/secondhand/oauth/InMemoryProviderRepository.java
  be/src/main/java/codesquad/secondhand/oauth/OauthAdapter.java
  be/src/main/java/codesquad/secondhand/oauth/OauthAttributes.java
  be/src/main/java/codesquad/secondhand/oauth/OauthProperties.java
  be/src/main/java/codesquad/secondhand/oauth/OauthProvider.java
  be/src/main/java/codesquad/secondhand/repository/MemberRepository.java
  be/src/main/java/codesquad/secondhand/service/OauthService.java
  be/src/main/resources/application-local.yml
  be/src/main/resources/schema.sql
  be/src/test/java/codesquad/secondhand/config/JasyptConfigTest.java
Labels: BE, feat

#223 [BE] CORS 설정 추가
  be/src/main/java/codesquad/secondhand/config/WebMvcConfig.java
  be/src/main/java/codesquad/secondhand/controller/ErrorTestController.java
Labels: BE, feat

#221 [FE] 52 홈에서 카테고리 버튼을 누르면 오른쪽에서 왼쪽으로
  fe/src/components/commons/Button/Button.tsx
  fe/src/components/commons/Button/ButtonStyle.ts
  fe/src/components/commons/Dropdown/Dropdown.tsx
  fe/src/components/commons/Dropdown/DropdownStyle.ts
  fe/src/components/commons/FilterBar/FilterBar.tsx
  fe/src/components/commons/FilterBar/FilterBarStyle.ts
  fe/src/components/commons/Layout/Layout.tsx
  fe/src/components/commons/Layout/LayoutStyle.ts
  fe/src/components/commons/Menu/Menu.tsx
  fe/src/components/commons/Portal/Portal.tsx
  fe/src/components/commons/Portal/PortalStyle.ts
  fe/src/mocks/data/items/category-page0.json
  fe/src/mocks/data/items/category-page1.json
  fe/src/mocks/handlers.ts
  fe/src/pages/DetailsPage/DetailsPage.tsx
  fe/src/pages/HomePage/CategoryPopup/CategoryElement/CategoryElement.tsx
  fe/src/pages/HomePage/CategoryPopup/CategoryElement/CategoryElementStyle.ts
  fe/src/pages/HomePage/CategoryPopup/CategoryPopup.tsx
  fe/src/pages/HomePage/CategoryPopup/CategoryPopupStyle.ts
  fe/src/pages/HomePage/HomePage.tsx
  fe/src/pages/WritePage/WritePage.tsx
  fe/src/services/apis/apis.ts
  fe/src/services/categories/categories.ts
  fe/src/services/items/items.ts
  fe/src/styles/GlobalStyle.ts
  fe/src/type-store/services/category.ts
Labels: FE, feat

#224 [BE] oauth, CORS 적용
  be/build.gradle
  be/src/main/java/codesquad/secondhand/config/OauthConfig.java
  be/src/main/java/codesquad/secondhand/config/WebMvcConfig.java
  be/src/main/java/codesquad/secondhand/controller/ErrorTestController.java
  be/src/main/java/codesquad/secondhand/controller/OauthController.java
  be/src/main/java/codesquad/secondhand/dto/oauth/MemberProfile.java
  be/src/main/java/codesquad/secondhand/dto/oauth/OauthLoginResponse.java
  be/src/main/java/codesquad/secondhand/dto/oauth/OauthTokenResponse.java
  be/src/main/java/codesquad/secondhand/entity/Member.java
  be/src/main/java/codesquad/secondhand/oauth/InMemoryProviderRepository.java
  be/src/main/java/codesquad/secondhand/oauth/OauthAdapter.java
  be/src/main/java/codesquad/secondhand/oauth/OauthAttributes.java
  be/src/main/java/codesquad/secondhand/oauth/OauthProperties.java
  be/src/main/java/codesquad/secondhand/oauth/OauthProvider.java
  be/src/main/java/codesquad/secondhand/repository/MemberRepository.java
  be/src/main/java/codesquad/secondhand/service/OauthService.java
  be/src/main/resources/application-local.yml
  be/src/main/resources/schema.sql
  be/src/test/java/codesquad/secondhand/config/JasyptConfigTest.java
Labels: BE
