Repository second-hand-team-01/second-hand, pull requests merged in 2023-07, with the labels that each got.

#343 [BE] 아이템 삭제 기능 구현
  be/src/main/java/codesquad/secondhand/entity/ItemImage.java
  be/src/main/java/codesquad/secondhand/service/ImageService.java
  be/src/main/java/codesquad/secondhand/service/ItemService.java
  be/src/main/resources/schema.sql
Labels: BE

#344 [BE] 이미지 수정 기능 구현
  be/src/main/java/codesquad/secondhand/controller/ItemController.java
  be/src/main/java/codesquad/secondhand/dto/item/ItemDetailReturnDto.java
  be/src/main/java/codesquad/secondhand/entity/Item.java
  be/src/main/java/codesquad/secondhand/service/ItemService.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
Labels: bug, BE

#348 [BE] docker file timezone 추가
  Dockerfile.be
  be/src/main/java/codesquad/secondhand/controller/MemberController.java
  be/src/main/java/codesquad/secondhand/util/IpSearcher.java
Labels: BE

#353 [FE] 상품 수정에서 이미지 수정 및 상세 페이지 시간 표시
  fe/src/App.tsx
  fe/src/components/commons/FilterBar/FilterBar.tsx
  fe/src/components/commons/ImgPreview/ImgElement/ImgElement.tsx
  fe/src/components/commons/ImgPreview/ImgPreview.tsx
  fe/src/components/commons/LocationPopup/LocationPopup.tsx
  fe/src/pages/HomePage/HomePage.tsx
  fe/src/pages/LoginPage/LoginPage.tsx
  fe/src/pages/SignUpPage/SignUpPage.tsx
  fe/src/pages/WritePage/WritePage.tsx
  fe/src/services/items/items.ts
  fe/src/services/items/write.ts
  fe/src/type-store/services/items.ts
Labels: refactor, FE, feat

#354 [FE] FE -> DEV
  fe/src/App.tsx
  fe/src/components/commons/FilterBar/FilterBar.tsx
  fe/src/components/commons/ImgPreview/ImgElement/ImgElement.tsx
  fe/src/components/commons/ImgPreview/ImgPreview.tsx
  fe/src/components/commons/LocationPopup/LocationPopup.tsx
  fe/src/pages/HomePage/HomePage.tsx
  fe/src/pages/LoginPage/LoginPage.tsx
  fe/src/pages/SignUpPage/SignUpPage.tsx
  fe/src/pages/WritePage/WritePage.tsx
  fe/src/services/items/items.ts
  fe/src/services/items/write.ts
  fe/src/type-store/services/items.ts
Labels: FE

#355 [FE] DEV -> MAIN
  fe/src/App.tsx
  fe/src/components/commons/FilterBar/FilterBar.tsx
  fe/src/components/commons/ImgPreview/ImgElement/ImgElement.tsx
  fe/src/components/commons/ImgPreview/ImgPreview.tsx
  fe/src/components/commons/LocationPopup/LocationPopup.tsx
  fe/src/pages/HomePage/HomePage.tsx
  fe/src/pages/LoginPage/LoginPage.tsx
  fe/src/pages/SignUpPage/SignUpPage.tsx
  fe/src/pages/WritePage/WritePage.tsx
  fe/src/services/items/items.ts
  fe/src/services/items/write.ts
  fe/src/type-store/services/items.ts
Labels: FE

#356 [BE] 조회수 증가만을 위한 Partial Update 적용
  be/src/main/java/codesquad/secondhand/controller/ItemController.java
  be/src/main/java/codesquad/secondhand/entity/Item.java
  be/src/main/java/codesquad/secondhand/service/ItemService.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
Labels: BE

#357 [BE] 조회수 증가만을 위한 Partial Update 적용
  be/src/main/java/codesquad/secondhand/controller/ItemController.java
  be/src/main/java/codesquad/secondhand/entity/Item.java
  be/src/main/java/codesquad/secondhand/service/ItemService.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
Labels: BE

#358 [BE] 조회수 증가만을 위한 Partial Update 적용
  be/src/main/java/codesquad/secondhand/controller/ItemController.java
  be/src/main/java/codesquad/secondhand/entity/Item.java
  be/src/main/java/codesquad/secondhand/service/ItemService.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
Labels: BE

#359 [iOS] Feat: 제품 상세 페이지 이미지 캐싱 기능 추가
  iOS/SecondHand/SecondHand.xcodeproj/project.pbxproj
  iOS/SecondHand/SecondHand/Detail/DetailRepository.swift
  iOS/SecondHand/SecondHand/Detail/DetailUseCase.swift
  iOS/SecondHand/SecondHand/Detail/DetailViewController.swift
  iOS/SecondHand/SecondHand/Detail/UI/CommunicationInfoView.swift
  iOS/SecondHand/SecondHand/Detail/UI/DetailContentView.swift
  iOS/SecondHand/SecondHand/Detail/UI/DetailToolbar.swift
  iOS/SecondHand/SecondHand/Detail/UI/ProductImageViewer.swift
  iOS/SecondHand/SecondHand/Detail/UI/ProductInfoView.swift
  iOS/SecondHand/SecondHand/FormatPriceGenerator.swift
  iOS/SecondHand/SecondHand/PassedTimeGenerator.swift
Labels: iOS

#360 [iOS] 좋아요 버튼 클릭 이벤트 구현
  iOS/SecondHand/SecondHand.xcodeproj/project.pbxproj
  iOS/SecondHand/SecondHand/Detail/DetailLocalDataSource.swift
  iOS/SecondHand/SecondHand/Detail/DetailModel.swift
  iOS/SecondHand/SecondHand/Detail/DetailRemoteDataSource.swift
  iOS/SecondHand/SecondHand/Detail/DetailRepository.swift
  iOS/SecondHand/SecondHand/Detail/DetailUseCase.swift
  iOS/SecondHand/SecondHand/Detail/DetailViewController.swift
  iOS/SecondHand/SecondHand/Detail/FavoriteResponseDTO.swift
  iOS/SecondHand/SecondHand/Detail/UI/DetailContentView.swift
  iOS/SecondHand/SecondHand/Detail/UI/DetailToolbar.swift
  iOS/SecondHand/SecondHand/Detail/UI/ProductImageViewer.swift
  iOS/SecondHand/SecondHand/Extension/Notification+Name.swift
  iOS/SecondHand/SecondHand/ItemList/ItemListViewController.swift
  iOS/SecondHand/SecondHand/Network/NetworkError.swift
Labels: iOS

#361 [BE] 주소 ID 반환기능 추가
  be/build.gradle
  be/src/main/java/codesquad/secondhand/controller/LocationController.java
  be/src/main/java/codesquad/secondhand/controller/MemberController.java
  be/src/main/java/codesquad/secondhand/dto/item/ItemDetailReturnDto.java
  be/src/main/java/codesquad/secondhand/dto/location/LocationListDto.java
  be/src/main/java/codesquad/secondhand/dto/oauth/MemberProfile.java
  be/src/main/java/codesquad/secondhand/entity/Item.java
  be/src/main/java/codesquad/secondhand/entity/Location.java
  be/src/main/java/codesquad/secondhand/repository/ItemRepository.java
  be/src/main/java/codesquad/secondhand/repository/LocationRepository.java
  be/src/main/java/codesquad/secondhand/service/ItemService.java
  be/src/main/java/codesquad/secondhand/service/LocationService.java
  be/src/main/java/codesquad/secondhand/util/IpSearcher.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
  be/src/test/java/codesquad/secondhand/config/TestDummyData.java
Labels: BE

#362 [BE] 주소 ID 반환기능 추가
  be/build.gradle
  be/src/main/java/codesquad/secondhand/controller/LocationController.java
  be/src/main/java/codesquad/secondhand/controller/MemberController.java
  be/src/main/java/codesquad/secondhand/dto/item/ItemDetailReturnDto.java
  be/src/main/java/codesquad/secondhand/dto/location/LocationListDto.java
  be/src/main/java/codesquad/secondhand/dto/oauth/MemberProfile.java
  be/src/main/java/codesquad/secondhand/entity/Item.java
  be/src/main/java/codesquad/secondhand/entity/Location.java
  be/src/main/java/codesquad/secondhand/repository/ItemRepository.java
  be/src/main/java/codesquad/secondhand/repository/LocationRepository.java
  be/src/main/java/codesquad/secondhand/service/ItemService.java
  be/src/main/java/codesquad/secondhand/service/LocationService.java
  be/src/main/java/codesquad/secondhand/util/IpSearcher.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
  be/src/test/java/codesquad/secondhand/config/TestDummyData.java
Labels: BE

#363 [BE] 주소 ID 반환기능 추가
  be/build.gradle
  be/src/main/java/codesquad/secondhand/controller/LocationController.java
  be/src/main/java/codesquad/secondhand/controller/MemberController.java
  be/src/main/java/codesquad/secondhand/dto/item/ItemDetailReturnDto.java
  be/src/main/java/codesquad/secondhand/dto/location/LocationListDto.java
  be/src/main/java/codesquad/secondhand/dto/oauth/MemberProfile.java
  be/src/main/java/codesquad/secondhand/entity/Item.java
  be/src/main/java/codesquad/secondhand/entity/Location.java
  be/src/main/java/codesquad/secondhand/repository/ItemRepository.java
  be/src/main/java/codesquad/secondhand/repository/LocationRepository.java
  be/src/main/java/codesquad/secondhand/service/ItemService.java
  be/src/main/java/codesquad/secondhand/service/LocationService.java
  be/src/main/java/codesquad/secondhand/util/IpSearcher.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
  be/src/test/java/codesquad/secondhand/config/TestDummyData.java
Labels: BE
